version: '3.8'

services:
  my_service:
    image: rockylinux:8
    environment:
      - MY_DOCKER_CODE_USER=${MY_DOCKER_CODE_USER}  # Pass the host environment variable to the container
    volumes:
      - my-linux-code-mount:/home/${MY_DOCKER_CODE_USER}/
      - ./../config_data/sshd_config:/etc/ssh/sshd_config
      - ./../config_data/shared_migration:/shared_migration/
    ports:
      - "1994:22"
    command: >
      /bin/bash -c "id -u ${MY_DOCKER_CODE_USER} &>/dev/null || useradd -m ${MY_DOCKER_CODE_USER} &&
                dnf -y install sudo openssh-server ncurses procps gcc gcc-c++ openssh-clients perl make python3.12 python2 cmake dos2unix openssl-devel &&
                dos2unix /home/${MY_DOCKER_CODE_USER}/start_setup.sh &&
                echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/wheel &&
                echo '${MY_DOCKER_CODE_USER} ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/${MY_DOCKER_CODE_USER} &&
                ssh-keygen -A &&
                echo 'root:password' | chpasswd &&
                echo '${MY_DOCKER_CODE_USER}:password' | chpasswd &&
                /usr/sbin/sshd -D"

volumes:
  my-linux-code-mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../user_data/

