version: '3.8'

services:
  my_service:
    image: rockylinux:8
    environment:
      - MY_DOCKER_USER=${MY_DOCKER_USER}  # Pass the host environment variable to the container
    volumes:
      - my-linux-code-mount:/${MY_DOCKER_USER}/
      - ./sshd_config:/etc/ssh/sshd_config
      - ./shared_migration:/shared_migration/
    ports:
      - "1994:22"
    command: >
      /bin/bash -c "id -u ${MY_DOCKER_USER} &>/dev/null || useradd -m ${MY_DOCKER_USER} && 
                dnf -y install openssh-server && 
                ssh-keygen -A && 
                echo 'root:password' | chpasswd && 
                echo '${MY_DOCKER_USER}:password' | chpasswd && 
                /usr/sbin/sshd -D"

volumes:
  my-linux-code-mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./oms-code/

